spring:
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: iphash://serviceA
          predicates:
            - Path=/service/*
    loadbalancer:
      health-check:
        path:
          serviceA: /

