spring:
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: iphash://serviceA
          predicates:
            - Path=/service/**
    loadbalancer:
      health-check:
        path:
          serviceA: /
        initial-delay: 1000
        interval: 10000
    discovery:
      client:
        simple:
          instances:
            serviceA:
              - uri: http://www.tanrd.com
